const CONSTANTES = {
    'ADD_LOG':'ADD_LOG',
    'SET_LOG':'SET_LOG',
    'SET_DOCUMENTOS':'SET_DOCUMENTOS',
    'SET_MENU':'SET_MENU',
    'SET_PERFIL':'SET_PERFIL',



    'SET_VALOR_CONTROL':'SET_VALOR_CONTROL',
    'INSERT_VALOR_CONTROL':'INSERT_VALOR_CONTROL',
    'CLEAR_VALOR_CONTROL':'CLEAR_VALOR_CONTROL',

    'SET_CHECK_ACTIVO':'SET_CHECK_ACTIVO',

    'INSERT_VALOR_CONTROL':'INSERT_VALOR_CONTROL',
    'CLEAR_VALOR_CONTROL':'CLEAR_VALOR_CONTROL',

    'ADD_DOCUMENTO':'ADD_DOCUMENTO',
    'SEND_DOCUMENTO':'SEND_DOCUMENTO',
    'UPDATE_DOCUMENTO':'UPDATE_DOCUMENTO',

    'SET_NEW_ROW':'SET_NEW_ROW',

    'SET_CHECK_DEFAULT_VALUES':'SET_CHECK_DEFAULT_VALUES'
    
};

export default CONSTANTES;